var searchData=
[
  ['macos_0',['MacOS',['../d9/def/class_accel_byte_1_1_utils_1_1_infoware_1_1_mac_o_s.html',1,'AccelByte::Utils::Infoware']]],
  ['mainthreadawaiter_1',['MainThreadAwaiter',['../d1/de0/class_wait_for_update_1_1_main_thread_awaiter.html',1,'WaitForUpdate']]],
  ['mainthreadutil_2',['MainThreadUtil',['../db/d16/class_main_thread_util.html',1,'']]],
  ['make2fafactordefault_3',['Make2FAFactorDefault',['../dc/d3f/class_accel_byte_1_1_api_1_1_user.html#a1997370847b409e639a8e09a11fe0383',1,'AccelByte::Api::User']]],
  ['make2fafactordefaultoptionalparameters_4',['Make2FAFactorDefaultOptionalParameters',['../d5/dc6/class_accel_byte_1_1_models_1_1_make2_f_a_factor_default_optional_parameters.html',1,'AccelByte::Models']]],
  ['make2fafactordefaultparameter_5',['Make2FAFactorDefaultParameter',['../d1/d66/class_accel_byte_1_1_models_1_1_make2_f_a_factor_default_parameter.html',1,'AccelByte::Models']]],
  ['management_6',['Management',['../de/d3f/group___server_user.html',1,'Server User Management'],['../d2/dcd/quickstart.html#autotoc_md17',1,'Session Management']]],
  ['matchendreason_7',['MatchEndReason',['../d6/d84/class_accel_byte_1_1_models_1_1_match_end_reason.html',1,'AccelByte::Models']]],
  ['matchinfoendedoptionalparameters_8',['MatchInfoEndedOptionalParameters',['../df/da4/class_accel_byte_1_1_models_1_1_match_info_ended_optional_parameters.html',1,'AccelByte::Models']]],
  ['matchinfoid_9',['MatchInfoId',['../d2/dd0/class_accel_byte_1_1_models_1_1_match_info_id.html',1,'AccelByte::Models']]],
  ['matchinfooptionalparameters_10',['MatchInfoOptionalParameters',['../d9/d01/class_accel_byte_1_1_models_1_1_match_info_optional_parameters.html',1,'AccelByte::Models']]],
  ['matchinfoplayeroptionalparameters_11',['MatchInfoPlayerOptionalParameters',['../de/d11/class_accel_byte_1_1_models_1_1_match_info_player_optional_parameters.html',1,'AccelByte::Models']]],
  ['matchingally_12',['MatchingAlly',['../da/dff/class_accel_byte_1_1_models_1_1_matching_ally.html',1,'AccelByte::Models']]],
  ['matchmaking_13',['Multiplayer &amp;amp; Matchmaking',['../d2/d2a/group___multiplayer.html',1,'']]],
  ['matchmakingcode_14',['MatchmakingCode',['../df/dbe/class_accel_byte_1_1_models_1_1_matchmaking_code.html',1,'AccelByte::Models']]],
  ['matchmakingnotif_15',['MatchmakingNotif',['../d9/d86/class_accel_byte_1_1_models_1_1_matchmaking_notif.html',1,'AccelByte::Models']]],
  ['matchmakingnotifallies_16',['MatchmakingNotifAllies',['../df/df2/class_accel_byte_1_1_models_1_1_matchmaking_notif_allies.html',1,'AccelByte::Models']]],
  ['matchmakingoptionalparam_17',['MatchmakingOptionalParam',['../d4/dea/class_accel_byte_1_1_models_1_1_matchmaking_optional_param.html',1,'AccelByte::Models']]],
  ['matchmakingresult_18',['MatchmakingResult',['../de/d51/class_accel_byte_1_1_models_1_1_matchmaking_result.html',1,'AccelByte::Models']]],
  ['matchmakingv2_19',['MatchmakingV2',['../d1/df1/class_accel_byte_1_1_api_1_1_matchmaking_v2.html',1,'AccelByte::Api']]],
  ['matchmakingv2_2ecs_20',['MatchmakingV2.cs',['../d4/d99/_matchmaking_v2_8cs.html',1,'']]],
  ['matchmakingv2activeticket_21',['MatchmakingV2ActiveTicket',['../da/d94/class_accel_byte_1_1_models_1_1_matchmaking_v2_active_ticket.html',1,'AccelByte::Models']]],
  ['matchmakingv2activetickets_22',['MatchmakingV2ActiveTickets',['../dd/df2/class_accel_byte_1_1_models_1_1_matchmaking_v2_active_tickets.html',1,'AccelByte::Models']]],
  ['matchmakingv2api_23',['MatchmakingV2Api',['../d5/d22/class_accel_byte_1_1_api_1_1_matchmaking_v2_api.html',1,'AccelByte.Api.MatchmakingV2Api'],['../d5/d22/class_accel_byte_1_1_api_1_1_matchmaking_v2_api.html#aacecad131a4f3b8e0acba9f955a32c85',1,'AccelByte.Api.MatchmakingV2Api.MatchmakingV2Api()']]],
  ['matchmakingv2api_2ecs_24',['MatchmakingV2Api.cs',['../df/d9e/_matchmaking_v2_api_8cs.html',1,'']]],
  ['matchmakingv2backfillproposalnotification_25',['MatchmakingV2BackfillProposalNotification',['../dd/da9/class_accel_byte_1_1_models_1_1_matchmaking_v2_backfill_proposal_notification.html',1,'AccelByte::Models']]],
  ['matchmakingv2backfillproposalreceived_26',['MatchmakingV2BackfillProposalReceived',['../dd/de9/class_accel_byte_1_1_server_1_1_server_d_s_hub.html#a6f095b2647dea5fc4979486962e6a723',1,'AccelByte::Server::ServerDSHub']]],
  ['matchmakingv2createticketerror_27',['MatchmakingV2CreateTicketError',['../d0/d6e/class_accel_byte_1_1_models_1_1_matchmaking_v2_create_ticket_error.html',1,'AccelByte::Models']]],
  ['matchmakingv2createticketrequest_28',['MatchmakingV2CreateTicketRequest',['../de/d0b/class_accel_byte_1_1_models_1_1_matchmaking_v2_create_ticket_request.html',1,'AccelByte::Models']]],
  ['matchmakingv2createticketrequestoptionalparams_29',['MatchmakingV2CreateTicketRequestOptionalParams',['../d6/d56/class_accel_byte_1_1_models_1_1_matchmaking_v2_create_ticket_request_optional_params.html',1,'AccelByte::Models']]],
  ['matchmakingv2createticketresponse_30',['MatchmakingV2CreateTicketResponse',['../d3/da7/class_accel_byte_1_1_models_1_1_matchmaking_v2_create_ticket_response.html',1,'AccelByte::Models']]],
  ['matchmakingv2matchfound_31',['MatchmakingV2MatchFound',['../da/d7b/class_accel_byte_1_1_api_1_1_lobby.html#aefe5ed17179e9b985a7177c9a3febca2',1,'AccelByte::Api::Lobby']]],
  ['matchmakingv2matchfoundnotification_32',['MatchmakingV2MatchFoundNotification',['../d9/de9/class_accel_byte_1_1_models_1_1_matchmaking_v2_match_found_notification.html',1,'AccelByte::Models']]],
  ['matchmakingv2matchmakingcanceled_33',['MatchmakingV2MatchmakingCanceled',['../da/d7b/class_accel_byte_1_1_api_1_1_lobby.html#add951402833757c4cfdc060b5778c451',1,'AccelByte::Api::Lobby']]],
  ['matchmakingv2matchmakingcancelednotification_34',['MatchmakingV2MatchmakingCanceledNotification',['../d7/d8f/class_accel_byte_1_1_models_1_1_matchmaking_v2_matchmaking_canceled_notification.html',1,'AccelByte::Models']]],
  ['matchmakingv2matchmakingstarted_35',['MatchmakingV2MatchmakingStarted',['../da/d7b/class_accel_byte_1_1_api_1_1_lobby.html#a263595754c0ae76be840827143f23002',1,'AccelByte::Api::Lobby']]],
  ['matchmakingv2matchmakingstartednotification_36',['MatchmakingV2MatchmakingStartedNotification',['../da/d27/class_accel_byte_1_1_models_1_1_matchmaking_v2_matchmaking_started_notification.html',1,'AccelByte::Models']]],
  ['matchmakingv2matchticketstatus_37',['MatchmakingV2MatchTicketStatus',['../da/d8d/class_accel_byte_1_1_models_1_1_matchmaking_v2_match_ticket_status.html',1,'AccelByte::Models']]],
  ['matchmakingv2metrics_38',['MatchmakingV2Metrics',['../de/dc7/class_accel_byte_1_1_models_1_1_matchmaking_v2_metrics.html',1,'AccelByte::Models']]],
  ['matchmakingv2models_2ecs_39',['MatchmakingV2Models.cs',['../d8/df8/_matchmaking_v2_models_8cs.html',1,'']]],
  ['matchmakingv2proposedproposal_40',['MatchmakingV2ProposedProposal',['../d9/d5f/class_accel_byte_1_1_models_1_1_matchmaking_v2_proposed_proposal.html',1,'AccelByte::Models']]],
  ['matchmakingv2serverclaimed_41',['MatchmakingV2ServerClaimed',['../dd/de9/class_accel_byte_1_1_server_1_1_server_d_s_hub.html#a72f4295635af60ca4eb8552ca0ecc4d1',1,'AccelByte::Server::ServerDSHub']]],
  ['matchmakingv2ticket_42',['MatchmakingV2Ticket',['../dc/d97/class_accel_byte_1_1_models_1_1_matchmaking_v2_ticket.html',1,'AccelByte::Models']]],
  ['matchmakingv2ticketexpired_43',['MatchmakingV2TicketExpired',['../da/d7b/class_accel_byte_1_1_api_1_1_lobby.html#a5bf228794beef13bd1c3e376a3d498b1',1,'AccelByte::Api::Lobby']]],
  ['matchmakingv2ticketexpirednotification_44',['MatchmakingV2TicketExpiredNotification',['../db/dca/class_accel_byte_1_1_models_1_1_matchmaking_v2_ticket_expired_notification.html',1,'AccelByte::Models']]],
  ['matchparty_45',['MatchParty',['../d5/d3d/class_accel_byte_1_1_models_1_1_match_party.html',1,'AccelByte::Models']]],
  ['matchpool_46',['MatchPool',['../d2/d62/class_accel_byte_1_1_models_1_1_get_user_matchmaking_tickets_optional_parameters.html#a1afd7a353f301f4129091d24473eaaa3',1,'AccelByte::Models::GetUserMatchmakingTicketsOptionalParameters']]],
  ['matchrequest_47',['MatchRequest',['../d6/df8/class_accel_byte_1_1_models_1_1_match_request.html',1,'AccelByte::Models']]],
  ['md5crypto_48',['MD5Crypto',['../dc/d04/class_accel_byte_1_1_core_1_1_m_d5_crypto.html',1,'AccelByte::Core']]],
  ['md5crypto_2ecs_49',['MD5Crypto.cs',['../d7/d54/_m_d5_crypto_8cs.html',1,'']]],
  ['mediatype_50',['MediaType',['../df/d07/class_accel_byte_1_1_core_1_1_media_type.html',1,'AccelByte::Core']]],
  ['mediatype_2ecs_51',['MediaType.cs',['../d5/d9e/_media_type_8cs.html',1,'']]],
  ['memberrole_52',['MemberRole',['../da/d16/class_accel_byte_1_1_models_1_1_member_role.html',1,'AccelByte::Models']]],
  ['memberrolepermission_53',['MemberRolePermission',['../d4/d5c/class_accel_byte_1_1_models_1_1_member_role_permission.html',1,'AccelByte::Models']]],
  ['message_54',['Message',['../dd/def/class_accel_byte_1_1_core_1_1_error.html#aa9bed53f136fa916c0e59775e0100529',1,'AccelByte.Core.Error.Message'],['../d4/d16/class_accel_byte_1_1_models_1_1_result_error_optional_parameters.html#a591458ad1d867d8ec881927959b2201f',1,'AccelByte.Models.ResultErrorOptionalParameters.Message']]],
  ['messagevariables_55',['MessageVariables',['../d4/d16/class_accel_byte_1_1_models_1_1_result_error_optional_parameters.html#a0374418a137477aec300501cdd234ce6',1,'AccelByte::Models::ResultErrorOptionalParameters']]],
  ['messagevariables_56',['messageVariables',['../dd/def/class_accel_byte_1_1_core_1_1_error.html#a39d644c3ddd9c1b8550cce41589a32cc',1,'AccelByte::Core::Error']]],
  ['messagingsystemmessage_57',['MessagingSystemMessage',['../d4/d78/struct_accel_byte_1_1_models_1_1_messaging_system_message.html',1,'AccelByte::Models']]],
  ['metadata_58',['Metadata',['../d7/d1b/class_accel_byte_1_1_models_1_1_invite_user_to_party_optional_parameters.html#a26f1ddd1498eb5a3f89c34cbff084554',1,'AccelByte.Models.InviteUserToPartyOptionalParameters.Metadata'],['../d4/df3/class_accel_byte_1_1_models_1_1_invite_user_to_game_session_optional_parameters.html#a996fd886ea62acc39a86861cc7b69907',1,'AccelByte.Models.InviteUserToGameSessionOptionalParameters.Metadata']]],
  ['metadataoptionalparamsbase_59',['MetadataOptionalParamsBase',['../de/d22/class_accel_byte_1_1_models_1_1_metadata_optional_params_base.html',1,'AccelByte::Models']]],
  ['miscellaneous_60',['Miscellaneous',['../d2/d31/class_accel_byte_1_1_api_1_1_miscellaneous.html',1,'AccelByte::Api']]],
  ['miscellaneous_2ecs_61',['Miscellaneous.cs',['../d2/dab/_miscellaneous_8cs.html',1,'']]],
  ['miscellaneousmodels_2ecs_62',['MiscellaneousModels.cs',['../d7/d16/_miscellaneous_models_8cs.html',1,'']]],
  ['missionendedoptionalparameters_63',['MissionEndedOptionalParameters',['../de/dbf/class_accel_byte_1_1_models_1_1_mission_ended_optional_parameters.html',1,'AccelByte::Models']]],
  ['missionid_64',['MissionId',['../d2/d32/class_accel_byte_1_1_models_1_1_mission_id.html',1,'AccelByte::Models']]],
  ['missioninstanceid_65',['MissionInstanceId',['../d5/d1f/class_accel_byte_1_1_models_1_1_mission_instance_id.html',1,'AccelByte::Models']]],
  ['missionstartedoptionalparameters_66',['MissionStartedOptionalParameters',['../d1/d3c/class_accel_byte_1_1_models_1_1_mission_started_optional_parameters.html',1,'AccelByte::Models']]],
  ['missionstep_67',['MissionStep',['../dd/d0f/class_accel_byte_1_1_models_1_1_mission_step.html',1,'AccelByte::Models']]],
  ['missionstependedoptionalparameters_68',['MissionStepEndedOptionalParameters',['../db/d29/class_accel_byte_1_1_models_1_1_mission_step_ended_optional_parameters.html',1,'AccelByte::Models']]],
  ['missionsuccess_69',['MissionSuccess',['../dd/d90/class_accel_byte_1_1_models_1_1_mission_success.html',1,'AccelByte::Models']]],
  ['mobile_2ecs_70',['Mobile.cs',['../de/d22/_mobile_8cs.html',1,'']]],
  ['modelcollection_2ecs_71',['ModelCollection.cs',['../dd/db4/_model_collection_8cs.html',1,'']]],
  ['models_72',['Data Models',['../da/d23/group___models.html',1,'']]],
  ['modifycontent_73',['ModifyContent',['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#ad24eb4826fff82a98360a9f1e1e8be17',1,'AccelByte.Api.UGC.ModifyContent(string channelId, string contentId, UGCUpdateRequest ModifyRequest, ResultCallback&lt; UGCResponse &gt; callback)'],['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#afc9695f28f80c9ebf29bea2a1488dac9',1,'AccelByte.Api.UGC.ModifyContent(string channelId, string contentId, UGCRequest ModifyRequest, ResultCallback&lt; UGCResponse &gt; callback, bool updateContent=false)'],['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#a8faac2dfd9ebccc451bd8d55f50f65e9',1,'AccelByte.Api.UGC.ModifyContent(string channelId, string contentId, string name, string type, string subtype, string[] tags, byte[] preview, string fileExtension, ResultCallback&lt; UGCResponse &gt; callback, string contentType=&quot;application/octet-stream&quot;, bool updateContent=false)']]],
  ['modifycontentbysharecode_74',['ModifyContentByShareCode',['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#a9409090a74fe4dcb0c61041c022500b3',1,'AccelByte.Api.UGC.ModifyContentByShareCode()'],['../d5/dc2/class_accel_byte_1_1_server_1_1_server_u_g_c.html#a6ff1cd933da65e97ce59a1afa2247e0f',1,'AccelByte.Server.ServerUGC.ModifyContentByShareCode()']]],
  ['modifycontentv2_75',['ModifyContentV2',['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#a74bb995f6f3de34e2a5f1948cb38c73d',1,'AccelByte::Api::UGC']]],
  ['modifystagingcontentbycontentid_76',['ModifyStagingContentByContentId',['../dc/d18/class_accel_byte_1_1_api_1_1_u_g_c.html#a629f63964bcdebdc7faa1bc6276f2ee1',1,'AccelByte::Api::UGC']]],
  ['modifyugcrequestv2_77',['ModifyUGCRequestV2',['../d0/d7d/class_accel_byte_1_1_models_1_1_modify_u_g_c_request_v2.html',1,'AccelByte::Models']]],
  ['modules_2edox_78',['modules.dox',['../dc/d66/modules_8dox.html',1,'']]],
  ['monetization_79',['Commerce &amp;amp; Monetization',['../de/d45/group___commerce.html',1,'']]],
  ['moveitemsbetweeninventories_80',['MoveItemsBetweenInventories',['../dc/ddc/interface_accel_byte_1_1_api_1_1_interface_1_1_i_client_inventory.html#a67035709401ed355c9ec03000fc623fa',1,'AccelByte.Api.Interface.IClientInventory.MoveItemsBetweenInventories()'],['../d2/d8b/class_accel_byte_1_1_api_1_1_inventory.html#a9d0fe6af19be87f43f73f927e13ccc2c',1,'AccelByte.Api.Inventory.MoveItemsBetweenInventories()']]],
  ['moveuseritemrequestdata_81',['MoveUserItemRequestData',['../d2/deb/class_accel_byte_1_1_models_1_1_move_user_item_request_data.html',1,'AccelByte::Models']]],
  ['moveuseritemresponsedata_82',['MoveUserItemResponseData',['../d5/d37/class_accel_byte_1_1_models_1_1_move_user_item_response_data.html',1,'AccelByte::Models']]],
  ['moveuseritemsbetweeninventoriespayload_83',['MoveUserItemsBetweenInventoriesPayload',['../db/dbb/class_accel_byte_1_1_models_1_1_move_user_items_between_inventories_payload.html',1,'AccelByte::Models']]],
  ['moveuseritemsbetweeninventoriesrequest_84',['MoveUserItemsBetweenInventoriesRequest',['../dd/d29/class_accel_byte_1_1_models_1_1_move_user_items_between_inventories_request.html',1,'AccelByte::Models']]],
  ['moveuseritemsbetweeninventoriesresponse_85',['MoveUserItemsBetweenInventoriesResponse',['../df/d0a/class_accel_byte_1_1_models_1_1_move_user_items_between_inventories_response.html',1,'AccelByte::Models']]],
  ['multiconfigs_86',['MultiConfigs',['../d0/dfd/class_accel_byte_1_1_models_1_1_multi_configs.html',1,'AccelByte::Models']]],
  ['multilanguageachievement_87',['MultiLanguageAchievement',['../d7/d1d/class_accel_byte_1_1_models_1_1_multi_language_achievement.html',1,'AccelByte::Models']]],
  ['multioauthconfigs_88',['MultiOAuthConfigs',['../db/d53/class_accel_byte_1_1_models_1_1_multi_o_auth_configs.html',1,'AccelByte::Models']]],
  ['multiplayer_89',['Server Multiplayer',['../d6/d92/group___server_multiplayer.html',1,'']]],
  ['multiplayer_20matchmaking_90',['Multiplayer &amp;amp; Matchmaking',['../d2/d2a/group___multiplayer.html',1,'']]],
  ['multiple_20api_20clients_91',['Multiple API Clients',['../d2/dcd/quickstart.html#autotoc_md21',1,'']]],
  ['multiserverconfigs_92',['MultiServerConfigs',['../da/db4/class_accel_byte_1_1_models_1_1_multi_server_configs.html',1,'AccelByte::Models']]],
  ['mutegroupchatrequest_93',['MuteGroupChatRequest',['../db/d5d/class_accel_byte_1_1_models_1_1_mute_group_chat_request.html',1,'AccelByte::Models']]],
  ['mutegroupuserchat_94',['MuteGroupUserChat',['../d6/d2d/class_accel_byte_1_1_api_1_1_chat.html#aa13dbfb75ad4afa9c1af4e235ebfdef4',1,'AccelByte::Api::Chat']]]
];
