var searchData=
[
  ['waitaframecommand_2ecs_0',['WaitAFrameCommand.cs',['../da/da2/_wait_a_frame_command_8cs.html',1,'']]],
  ['waitforbackgroundthread_1',['WaitForBackgroundThread',['../d1/d64/class_native_web_socket_1_1_wait_for_background_thread.html',1,'NativeWebSocket']]],
  ['waitforupdate_2',['WaitForUpdate',['../d2/d17/class_wait_for_update.html',1,'']]],
  ['waittimecommand_2ecs_3',['WaitTimeCommand.cs',['../d6/dfe/_wait_time_command_8cs.html',1,'']]],
  ['wallet_4',['Wallet',['../d8/d18/class_accel_byte_1_1_api_1_1_wallet.html',1,'AccelByte::Api']]],
  ['wallet_2ecs_5',['Wallet.cs',['../de/dc7/_wallet_8cs.html',1,'']]],
  ['walletapi_6',['WalletApi',['../d9/d2b/class_accel_byte_1_1_api_1_1_wallet_api.html',1,'AccelByte::Api']]],
  ['walletapi_2ecs_7',['WalletApi.cs',['../df/df7/_wallet_api_8cs.html',1,'']]],
  ['walletinfo_8',['WalletInfo',['../dc/dd2/class_accel_byte_1_1_models_1_1_wallet_info.html',1,'AccelByte::Models']]],
  ['walletinforesponse_9',['WalletInfoResponse',['../d5/dc7/class_accel_byte_1_1_models_1_1_wallet_info_response.html',1,'AccelByte::Models']]],
  ['wallettransactioninfo_10',['WalletTransactionInfo',['../d8/dfa/class_accel_byte_1_1_models_1_1_wallet_transaction_info.html',1,'AccelByte::Models']]],
  ['wallettransactionpagingslicedresult_11',['WalletTransactionPagingSlicedResult',['../d7/d19/class_accel_byte_1_1_models_1_1_wallet_transaction_paging_sliced_result.html',1,'AccelByte::Models']]],
  ['webrequestscheduler_2ecs_12',['WebRequestScheduler.cs',['../d3/d7a/_web_request_scheduler_8cs.html',1,'']]],
  ['webrequesttask_2ecs_13',['WebRequestTask.cs',['../d2/dae/_web_request_task_8cs.html',1,'']]],
  ['websocket_14',['WebSocket',['../d7/d11/class_native_web_socket_1_1_web_socket.html',1,'NativeWebSocket']]],
  ['websocket_2ecs_15',['WebSocket.cs',['../d6/daa/_core_2_websocket_2_web_socket_8cs.html',1,'(Global Namespace)'],['../de/d24/_third_parties_2_native_web_socket_2_web_socket_8cs.html',1,'(Global Namespace)']]],
  ['websocketconnectoptionalparameters_16',['WebsocketConnectOptionalParameters',['../d1/d2f/class_accel_byte_1_1_models_1_1_websocket_connect_optional_parameters.html',1,'AccelByte::Models']]],
  ['websocketerrortypes_2ecs_17',['WebSocketErrorTypes.cs',['../db/d99/_web_socket_error_types_8cs.html',1,'']]],
  ['websocketexception_18',['WebSocketException',['../df/d11/class_accel_byte_1_1_core_1_1_web_socket_exception.html',1,'AccelByte.Core.WebSocketException'],['../db/d61/class_native_web_socket_1_1_web_socket_exception.html',1,'NativeWebSocket.WebSocketException']]],
  ['websocketinvalidargumentexception_19',['WebSocketInvalidArgumentException',['../d0/d1d/class_native_web_socket_1_1_web_socket_invalid_argument_exception.html',1,'NativeWebSocket']]],
  ['websocketinvalidstateexception_20',['WebSocketInvalidStateException',['../db/d1c/class_accel_byte_1_1_core_1_1_web_socket_invalid_state_exception.html',1,'AccelByte.Core.WebSocketInvalidStateException'],['../d0/de0/class_native_web_socket_1_1_web_socket_invalid_state_exception.html',1,'NativeWebSocket.WebSocketInvalidStateException']]],
  ['websocketmodel_2ecs_21',['WebsocketModel.cs',['../df/d4b/_websocket_model_8cs.html',1,'']]],
  ['websocketunexpectedexception_22',['WebSocketUnexpectedException',['../d5/d4d/class_accel_byte_1_1_core_1_1_web_socket_unexpected_exception.html',1,'AccelByte.Core.WebSocketUnexpectedException'],['../d2/d19/class_native_web_socket_1_1_web_socket_unexpected_exception.html',1,'NativeWebSocket.WebSocketUnexpectedException']]],
  ['websocketurlbuilder_23',['WebsocketUrlBuilder',['../d1/d58/class_accel_byte_1_1_core_1_1_websocket_url_builder.html',1,'AccelByte::Core']]],
  ['websocketurlbuilder_2ecs_24',['WebSocketUrlBuilder.cs',['../d4/dc9/_web_socket_url_builder_8cs.html',1,'']]],
  ['websocketutils_2ecs_25',['WebsocketUtils.cs',['../dd/d4c/_websocket_utils_8cs.html',1,'']]],
  ['windows_26',['Windows',['../dc/d86/class_accel_byte_1_1_utils_1_1_infoware_1_1_windows.html',1,'AccelByte::Utils::Infoware']]],
  ['windowsmain_2ecs_27',['WindowsMain.cs',['../d9/dfe/_windows_main_8cs.html',1,'']]],
  ['with_20device_20id_28',['Login with Device ID',['../d2/dcd/quickstart.html#autotoc_md12',1,'']]],
  ['with_20email_20username_29',['Login with Email/Username',['../d2/dcd/quickstart.html#autotoc_md11',1,'']]],
  ['with_20platform_20token_30',['Login with Platform Token',['../d2/dcd/quickstart.html#autotoc_md13',1,'']]],
  ['withformparam_31',['WithFormParam',['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#a9caf36532b1382baa77696f2b2b56f69',1,'AccelByte::Core::HttpRequestBuilder']]],
  ['withpathparam_32',['WithPathParam',['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#a44117a051efb41ad9c38611edf637225',1,'AccelByte::Core::HttpRequestBuilder']]],
  ['withpathparams_33',['WithPathParams',['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#a8c110a2f4ce9662c80376d23f3f36b00',1,'AccelByte::Core::HttpRequestBuilder']]],
  ['withqueryparam_34',['WithQueryParam',['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#accd64f7dd75000a910459910914deaa3',1,'AccelByte.Core.HttpRequestBuilder.WithQueryParam(string key, string value)'],['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#a3c35b08f8d813b8b2dc15bb9fa37b7a4',1,'AccelByte.Core.HttpRequestBuilder.WithQueryParam(string key, ICollection&lt; string &gt; values)']]],
  ['withqueryparams_35',['WithQueryParams',['../de/daa/class_accel_byte_1_1_core_1_1_http_request_builder.html#ac283d9f0633d151e05f4eab36d032a77',1,'AccelByte::Core::HttpRequestBuilder']]],
  ['wrapperbase_36',['WrapperBase',['../df/d07/class_accel_byte_1_1_core_1_1_wrapper_base.html',1,'AccelByte::Core']]],
  ['wrapperbase_2ecs_37',['WrapperBase.cs',['../d5/d2d/_wrapper_base_8cs.html',1,'']]],
  ['writepartystorage_38',['WritePartyStorage',['../da/d7b/class_accel_byte_1_1_api_1_1_lobby.html#a290cb20acec9b3bc4acb1ad8013c91d2',1,'AccelByte.Api.Lobby.WritePartyStorage()'],['../da/ddf/class_accel_byte_1_1_server_1_1_server_lobby.html#a96b09ebcaded019ab7167bf1799f6fdc',1,'AccelByte.Server.ServerLobby.WritePartyStorage()']]],
  ['wsclosecode_39',['WsCloseCode',['../d1/d6e/namespace_accel_byte_1_1_core.html#aa5e23cb9a9d6108253923f0f4a00eb7b',1,'AccelByte::Core']]],
  ['wsmessagefragmentprocessor_40',['WsMessageFragmentProcessor',['../d2/d2a/class_core_1_1_ws_message_fragment_processor.html',1,'Core']]],
  ['wsmessagefragmentprocessor_2ecs_41',['WsMessageFragmentProcessor.cs',['../d4/db4/_ws_message_fragment_processor_8cs.html',1,'']]]
];
